#!/bin/bash

FILE=${1}

NAMES[0]=""
STATUSES[0]=""
GROSSES[0]=0

getPosition() {
#echo "${1}"
local POS=0
for N in ${NAMES[@]}
do
	if [[ "${NAMES[$POS]}" == "${1}" ]]; then
		echo $POS
		return
	fi
	POS=$[$POS + 1 ]
done

echo -1

}

POS=0
while read LINE
do
#	echo "$LINE"
	NAME=$(echo "$LINE" | cut -d ',' -f4 | sed 's/\"//g')
	if [[ $? -gt 0 ]]; then exit; fi
	STATUS=$(echo "$LINE" | cut -d ',' -f6 | sed 's/\"//g')
	GROSS=$(echo "$LINE" | cut -d ',' -f7 | sed 's/\"//g')
 
#	echo "$NAME $STATUS $GROSS"
	if [[ "${NAMES[@]}" == *"$NAME"* ]]; then
#		echo "duplicate detected"
		DUPPOS=$(getPosition "$NAME")
#		echo "duplicate pos = $DUPPOS"
		PGROSS=${GROSSES[$DUPPOS]}
#		echo "last gross = $PGROSS"
		GROSSES[$DUPPOS]=$(echo "$PGROSS + $GROSS" | bc )
#		echo "new gross = ${GROSSES[$DUPPOS]}"
	else
		if [[ "$NAME" == "" ]]; then
			continue
		fi
		NAMES[$POS]=$NAME
		GROSSES[$POS]=$GROSS
		POS=$[$POS + 1 ]
	fi
	
done < $FILE

POS=1

for NAME in ${NAMES[@]}
do
	if [[ "${NAMES[$POS]}" == "" ]]; then
		POS=$[$POS + 1]
		continue
	fi
	if [[ $(echo "${GROSSES[$POS]} >= 2" | bc) -gt 0 ]]; then
		NAMEVAR=$(echo  ${NAMES[$POS]} | awk '{print tolower($0)}' | sed 's/ /_/g')
		echo "${GROSSES[$POS]},${NAMES[$POS]},$NAMEVAR"
	fi
	POS=$[$POS + 1 ]
done
